<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @method User getRecord()
 * @method User findOneById()
 * @method User findOneBy()
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return UserTable
 *
 * @method User getRecord()
 *
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }
}