<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 *
 */
class User extends Base_User
{

    public function preInsert($event = null)
    {
        $this->salt = $this->generateSalt();
        $this->password = md5($this->password . $this->salt);
        $role = MiniMVC_Registry::getInstance()->rights->getRoleByKeyword('user');
        if ($role)
        {
            $this->role = $role;
        }
    }

    public function updatePassword()
    {
        $this->preInsert();
    }

    protected function generateSalt()
    {
        $salt = '';
        $chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"$%&/()=?@<>|}][{+#-.,*_:';

        $salt_length = rand(24,32);
        $chars_length = mb_strlen($chars, 'UTF-8') - 1;
        for ($i=0;$i<$salt_length;$i++)
        {
            $salt .= mb_substr($chars,rand(0, $chars_length), 1, 'UTF-8');
        }
        return $salt;
    }

    public function checkPassword($password)
    {
        if ($this->exists() && md5($password.$this['salt']) == $this['password'])
        {
            return true;
        }
        return false;
    }
}

