<?php

use Doctrine\ORM\EntityRepository;
/**
 * TestUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestUserRepository extends EntityRepository
{
}