<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addminimvctestexamplemodeltranslation extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('minimvc_test_example_model_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'primary' => true,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'blob',
              'length' => NULL,
             ),
             'lang' => 
             array(
              'fixed' => true,
              'primary' => true,
              'type' => 'string',
              'length' => 2,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('minimvc_test_example_model_translation');
    }
}