<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addminimvctestexamplemodel extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('minimvc_test_example_model', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'default_name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'status' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('minimvc_test_example_model');
    }
}