<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('minimvc_test_example_model_translation', 'mimi_1', array(
             'name' => 'mimi_1',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'minimvc_test_example_model',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('minimvc_test_example_model_translation', 'mimi_1');
    }
}