<?php

/**
 * DevFischArtTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DevFischArtTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DevFischArtTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DevFischArt');
    }
}