<?php

/**
 * DevFischTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DevFischTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DevFischTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DevFisch');
    }
}