<?php

/**
 * Base_DevFisch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $art
 * @property DevFischArt $DevFischArt
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_DevFisch extends MiniMVC_Model
{
    public function setTableDefinition()
    {
        $this->setTableName('dev_fisch');
        $this->hasColumn('name', 'string', 255, array(
             'default' => 'Fisch',
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('art', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DevFischArt', array(
             'local' => 'art',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}