<?php

/**
 * TestExampleModelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @method TestExampleModel getRecord()
 * @method User findOneById()
 * @method User findOneBy()
 */
class TestExampleModelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TestExampleModelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TestExampleModel');
    }

    public function getTranslatedRecord($id, $lang)
    {
        return $this->createQuery('a')->select('a.*, t.name as name, t.description as description')->leftJoin('a.Translation t')->where('a.id = ? and t.lang = ?')->execute(array($id, $lang))->getFirst();
    }
}